### ISSUE TITLE
Give user the ability to set which symbols to navigate between

### ISSUE THREAD

**Issue by mishkinf** [mishkinf/vscode-goto-next-previous-member#1]
Right now the extension navigates up and down all of the symbols. It would be useful to be able to limit the symbols to just certain symbols you care about. 

For instance, being able to navigate up and down the methods and classes without stopping at variables.

**Comment by kkorus** [comment]
@mishkinf  Good idea, I like it.

**Comment by georgejecook** [comment]
Is this going to get implemented? I'm really busy writing a plugin for brighscript, and use your great little extension. I'd love to commit a fix to allow us to configure 2 sets of hotkeys (functions/everything else); but I don't have time.

Do you think you'll get around to this?
