### ISSUE TITLE
Compatibility with Ruby Symbols

### ISSUE THREAD

**Issue by HenryMarshall** [mishkinf/vscode-goto-next-previous-member#15]
Per this instruction:
> Please report any missing extensions and I'll update the list.

I just wanted to report partial compatibility with [Ruby Symbols](https://marketplace.visualstudio.com/items?itemName=miguel-savignano.ruby-symbols). It only adds symbols for modules, class and methods, but that's all I wanted.

Thanks for making this extension, it's working great!

**Comment by mishkinf** [comment]
thank you for the tip. i can update the list! Glad you like it Henry. Share the extension with your coworkers! thank you
