### ISSUE TITLE
It jumps into export keyword instead of method name.

### ISSUE THREAD

**Issue by kkorus** [mishkinf/vscode-goto-next-previous-member#2]
It jumps into `export` keyword instead of method name (typescript).

![image](https://user-images.githubusercontent.com/2054009/41289965-4d43b30c-6e43-11e8-8591-31e7f091ebbf.png)

**Comment by mishkinf** [comment]
@kkorus Will need to investigate `vscode.executeDocumentSymbolProvider` to see what symbols typescript returns. I could set the ability to choose what type of symbols to navigate to.. that was a planned feature but I have been busy working on other things. Your desired functionality would be to navigate the cursor to right before the "b" in "buildConnectionString"?

**Comment by kkorus** [comment]
@mishkinf Yes, right before `b`.

**Comment by xinaesthete** [comment]
I find that in my (JS) code, it seems to jump to wherever a member is declared, even if it's something like a trivial local variable in a folded function... which then means that it unfolds the function, which is somewhat limiting usefulness for me just now.  I imagine this isn't the intended behaviour - looking at the screenshot above, I find it hard to believe it wouldn't unfold `buildConnectionString` and jump somewhere inside... it may of course be that the API deals better with well structured TypeScript than my rat's nest of JS ;)

I was going to file a separate issue, but this seems somewhat related.

**Comment by mishkinf** [comment]
@xinaesthete I believe it should be relatively simple to provide a way to customize what somebody would like it to stop at. I agree with your sentiment. Ive been ultra busy the past week or so but I will try get to it! If you want to submit a PR I am open to that too!

**Comment by xinaesthete** [comment]
Could be a way to dip my toes into VSCode extension dev... I might take a look, but no promises.

Cheers!

**Comment by kamenminkov** [comment]
Kind of related - I think there should be a way to skip access modifiers in TypeScript and go to the beginning of an actual identifier. Example:

```
class Foo {
	private bar(): void {

	}

	public baz(): void {

	}
}
```

As it is now, it would place the cursor in front of `private` and `public` whereas it would be (IMO) more useful to have it in front of `bar()` and `baz()` respectively.

Should I submit this as a separate issue?
