### ISSUE TITLE
modifies the edit history

### ISSUE THREAD

**Issue by balazser** [mishkinf/vscode-goto-next-previous-member#3]
thank you for the extension.
Did you experience that if I navigate through the members then do undo (CMD+Z) it steps back from the latest point to the newest one, then undo the modification?

vscode 1.25.1
Mac

**Comment by mishkinf** [comment]
That is very interesting. I will investigate it. Initial guess is that its a bug that has been introduced in VScode but maybe I have done something wrong on my end. Good catch @balazser
