### ISSUE TITLE
Please, ignore comments in Java

### ISSUE THREAD

**Issue by yaagma** [mishkinf/vscode-goto-next-previous-member#5]
In Java, when jumping to the next method, instead of going to "public", it goes to the comment above the method:

Example:
``` java
    public void f() {  
            // 1. Cursor HERE <<<<<<<<<<<<<<
    }

    // Comment          // 2 . Jumps HERE <<<<<<<<<
    public void g() {   // 3. Shoud jump HERE <<<<<<

    }
```

In javascript works ok.

Thanks for this GREAT extension.
Raúl

**Comment by mishkinf** [comment]
Publishing new version of extension 0.0.5 with the fix. Thank you again for your contributions!

**Comment by yaagma** [comment]
Thank you very much.
It works perfect now!!!
