### ISSUE TITLE
Cannot change keystrokes in JSON to "ctrl+ALT+up/down"

### ISSUE THREAD

**Issue by olegolegoleg** [mishkinf/vscode-goto-next-previous-member#8]
I cannot change the keystroke shortcuts from "_ctrl+up/down_" to "_ctrl+alt+up/down_" – new shortcuts are ignored. 
But what's interesting, change to "_ctrl+shift+up/down_".

```
    // Unbind the default shortcuts
    {
        "key": "ctrl+down",
        "command": "-gotoNextPreviousMember.nextMember"
    },
    {
        "key": "ctrl+up",
        "command": "-gotoNextPreviousMember.previousMember"
    },
    // Bind my shortcuts instead
    {
        "key": "ctrl+alt+down",
        "command": "gotoNextPreviousMember.nextMember"
    },
    {
        "key": "ctrl+alt+up",
        "command": "gotoNextPreviousMember.previousMember"
    }
```

It is any limitation with "**ALT**" key? I have tried several times, to be honest this is first time I change the keystrokes. Did I missed something?

**Comment by TheTastefulToastie** [comment]
I don't think this is an issue with this extension.
An extension can't change anything about the way VSCode binds it's keyboard shortcuts, it can only make new commands available to be bound (i.e. `gotoNextPreviousMember.nextMember`). So your problem likely lies elsewhere.

Have you tried assigning ctrl+alt+up/down to any other command to see if it works?

Have you tried the GUI shortcut editor? `File->Preferences->Keyboard Shortcuts`
Are there any other shortcuts bound to ctrl+alt+up/down? You can check this by searching "ctrl+alt+" in the GUI. Try unbinding them.

I've heard the alt key can behave strangely in VSCode on non-English keyboard layouts. Try another keyboard if possible to see if that's the cause.

Copy+pasting your config above into by `keybindings.json` worked fine for me on Windows & Linux with a UK layout keyboard.
